// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/johejo/ges/internal/application/usecase"
	"github.com/johejo/ges/internal/infrastructure/mysql"
	"github.com/johejo/ges/internal/interface/api/server"
	"github.com/johejo/ges/internal/interface/api/server/handler"
	"github.com/johejo/ges/internal/interface/api/server/router"
)

// Injectors from wire.go:

func NewServer() server.Server {
	db := mysql.OpenConnection()
	messageRepository := mysql.NewMessageRepository(db)
	messageUseCase := usecase.NewMessageUseCase(messageRepository)
	messageHandler := handler.NewMessageHandler(messageUseCase)
	appRouter := router.NewMessageRouter(messageHandler)
	httpHandler := router.New(appRouter)
	serverServer := server.New(httpHandler)
	return serverServer
}
