version: '3'
services:
  mysql:
    container_name: message-mysql
    image: 'mysql:8'
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: message
      MYSQL_PASSWORD: message
      MYSQL_DATABASE: messagedb
      TZ: Asia/Tokyo